//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] asmparse {
            get {
                object obj = ResourceManager.GetObject("asmparse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DILE {
            get {
                object obj = ResourceManager.GetObject("DILE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;opCodes&gt;
        ///	&lt;opCode name=&quot;Add&quot;&gt;
        ///		Adds two values and pushes the result onto the evaluation stack.
        ///	&lt;/opCode&gt;
        ///	&lt;opCode name=&quot;Add_Ovf&quot;&gt;
        ///		Adds two integers, performs an overflow check, and pushes the result onto the evaluation stack.
        ///	&lt;/opCode&gt;
        ///	&lt;opCode name=&quot;Add_Ovf_Un&quot;&gt;
        ///		Adds two unsigned integer values, performs an overflow check, and pushes the result onto the evaluation stack.
        ///	&lt;/opCode&gt;
        ///	&lt;opCode name=&quot;And&quot;&gt;
        ///		Computes the bitwise AND of two values and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpCodes {
            get {
                return ResourceManager.GetString("OpCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:files=&quot;http://sourceforge.net/api/files.rdf#&quot; xmlns:media=&quot;http://video.search.yahoo.com/mrss/&quot;&gt;
        ///	&lt;xsl:output method=&quot;html&quot; encoding=&quot;UTF-8&quot; doctype-public=&quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; doctype-system=&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;html&gt;
        ///			&lt;head&gt;
        ///				&lt;style type=&quot;text/css&quot;&gt;
        ///					.html,
        ///					body
        ///					{
        ///						overflow-x:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReleasesRssFeed {
            get {
                return ResourceManager.GetString("ReleasesRssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:output method=&quot;html&quot; encoding=&quot;UTF-8&quot; doctype-public=&quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; doctype-system=&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;html&gt;
        ///			&lt;head&gt;
        ///				&lt;style type=&quot;text/css&quot;&gt;
        ///					.html,
        ///						body
        ///					{
        ///						overflow-x: hidden;
        ///					}
        ///					
        ///					div.title
        ///					{
        ///						font-weight: bold;
        ///						padding-bottom: 5px;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RssFeed {
            get {
                return ResourceManager.GetString("RssFeed", resourceCulture);
            }
        }
    }
}
